import type { Order } from '../types/order';
import type { Branch, CartItem, Product, SizeOz } from '../types/menu';

export const COLORS = {
  primary: '#00704A',
  secondary: '#362415',
  background: '#FFFFFF',
  error: '#D32F2F',
  inactive: '#757575',
  surface: '#F5F5F5',
  accent: '#E8F5E9',
};

export const IMAGES = {
  lemonJuice: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVzaCUyMGxlbW9uJTIwanVpY2UlMjBkcmlua3xlbnwxfHx8fDE3NzI2OTAxNzZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
  latte: 'https://images.unsplash.com/photo-1680381724318-c8ac9fe3a484?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGVjaWFsdHklMjBjb2ZmZWUlMjBsYXR0ZSUyMGFydHxlbnwxfHx8fDE3NzI2MzA3MDN8MA&ixlib=rb-4.1.0&q=80&w=1080',
  icedTea: 'https://images.unsplash.com/photo-1596813890370-19f2a00b3388?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpY2VkJTIwdGVhJTIwYmV2ZXJhZ2V8ZW58MXx8fHwxNzcyNjg0MDM4fDA&ixlib=rb-4.1.0&q=80&w=1080',
  matcha: 'https://images.unsplash.com/photo-1708572727896-117b5ea25a86?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYXRjaGElMjBncmVlbiUyMHRlYSUyMGxhdHRlfGVufDF8fHx8MTc3MjYxNTgzOXww&ixlib=rb-4.1.0&q=80&w=1080',
  mango: 'https://images.unsplash.com/photo-1544510806-e28d3cd4d4e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW5nbyUyMHNtb290aGllJTIwdHJvcGljYWx8ZW58MXx8fHwxNzcyNjkwMTc4fDA&ixlib=rb-4.1.0&q=80&w=1080',
  espresso: 'https://images.unsplash.com/photo-1645445644664-8f44112f334c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlc3ByZXNzbyUyMGNvZmZlZSUyMGN1cHxlbnwxfHx8fDE3NzI2ODg4MTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
  frappe: 'https://images.unsplash.com/photo-1553649372-9d631caca7bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYXJhbWVsJTIwZnJhcHBlJTIwZHJpbmt8ZW58MXx8fHwxNzcyNjkwMTc5fDA&ixlib=rb-4.1.0&q=80&w=1080',
  mocha: 'https://images.unsplash.com/photo-1619286310410-a95de97b0aec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaG9jb2xhdGUlMjBtb2NoYSUyMGNvZmZlZXxlbnwxfHx8fDE3NzI2OTAxNzl8MA&ixlib=rb-4.1.0&q=80&w=1080',
  citrus: 'https://images.unsplash.com/photo-1643996322171-7a94b7acc9a7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcnVpdCUyMGp1aWNlJTIwY2l0cnVzJTIwb3JhbmdlfGVufDF8fHx8MTc3MjY5MDE4MHww&ixlib=rb-4.1.0&q=80&w=1080',
  shop: 'https://images.unsplash.com/photo-1631869404868-2ae8de2e7264?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3p5JTIwY29mZmVlJTIwc2hvcCUyMGludGVyaW9yJTIwd2FybXxlbnwxfHx8fDE3NzI2OTAxODJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
  coldBrew: 'https://images.unsplash.com/photo-1611477948234-a3c27435c72b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2xkJTIwYnJldyUyMGNvZmZlZSUyMGdsYXNzfGVufDF8fHx8MTc3MjY2NTM2OXww&ixlib=rb-4.1.0&q=80&w=1080',
};

export const branches: Branch[] = [
  { id: '1', name: 'SM City Cebu', address: 'North Reclamation Area, Cebu City', hours: '8:00 AM - 9:00 PM', available: true, brand: 'lehmuhn' },
  { id: '2', name: 'Ayala Center', address: 'Cebu Business Park, Cebu City', hours: '9:00 AM - 10:00 PM', available: true, brand: 'lehmuhn' },
  { id: '3', name: 'IT Park Branch', address: 'Lahug, Cebu City', hours: '7:00 AM - 11:00 PM', available: false, brand: 'lehmuhn' },
  { id: '4', name: 'Robinson Galleria', address: 'General Maxilom Ave, Cebu City', hours: '10:00 AM - 9:00 PM', available: true, brand: 'kohfee' },
  { id: '5', name: 'Banilad Town Centre', address: 'Gov. M. Cuenco Ave, Cebu City', hours: '8:00 AM - 8:00 PM', available: true, brand: 'kohfee' },
  { id: '6', name: 'Fuente Circle', address: 'Osme\u00f1a Blvd, Cebu City', hours: '6:00 AM - 10:00 PM', available: true, brand: 'kohfee' },
];

export const products: Product[] = [
  {
    id: 'lm-just-lehmuhn',
    storeId: 'lehmuhn',
    name: 'Just Leh-muhn',
    description: 'Classic cold blend with lemon, chia, and nata de coco.',
    basePrice: 69,
    priceBySizeOz: { 16: 69, 22: 89 },
    image: IMAGES.lemonJuice,
    drinkType: 'COLD',
    isPremium: false,
    defaultToppingsLabel: 'Lemon + Chia + Nata de coco',
    defaultToppingsCost: 15,
  },
  {
    id: 'lm-hot-healthy',
    storeId: 'lehmuhn',
    name: 'Hot and Healthy Leh-muhn',
    description: 'Warm wellness cup with selectable infusion profile.',
    basePrice: 99,
    priceBySizeOz: { 12: 99 },
    image: IMAGES.citrus,
    drinkType: 'HOT',
    hotOptions: ['Honey', 'Ginger', 'Pure lemon', 'Lemongrass'],
    isPremium: false,
  },
  {
    id: 'lm-premium-cold',
    storeId: 'lehmuhn',
    name: 'Premium Leh-muhn',
    description: 'Premium cold line with rotating flavor list.',
    basePrice: 89,
    priceBySizeOz: { 16: 89, 22: 109 },
    image: IMAGES.citrus,
    drinkType: 'COLD',
    isPremium: true,
    defaultToppingsLabel: 'Premium fruit mix',
    defaultToppingsCost: 15,
  },
  {
    id: 'lm-blended-strawberry',
    storeId: 'lehmuhn',
    name: 'Blended Strawberry Leh-muhn',
    description: 'Strawberry forward blended Leh-muhn.',
    basePrice: 135,
    priceBySizeOz: { 16: 135 },
    image: IMAGES.mango,
    drinkType: 'BLENDED',
    isPremium: false,
  },
  {
    id: 'lm-blended-mixed-berries',
    storeId: 'lehmuhn',
    name: 'Blended Mixed Berries Leh-muhn',
    description: 'Balanced berry blend with tart finish.',
    basePrice: 135,
    priceBySizeOz: { 16: 135 },
    image: IMAGES.mango,
    drinkType: 'BLENDED',
    isPremium: false,
  },
  {
    id: 'lm-blended-cranberry',
    storeId: 'lehmuhn',
    name: 'Blended Cranberry Leh-muhn',
    description: 'Cranberry-heavy blend with bright citrus notes.',
    basePrice: 135,
    priceBySizeOz: { 16: 135 },
    image: IMAGES.mango,
    drinkType: 'BLENDED',
    isPremium: false,
  },
  {
    id: 'lm-blended-raspberry',
    storeId: 'lehmuhn',
    name: 'Blended Raspberry Leh-muhn',
    description: 'Raspberry infused blended series favorite.',
    basePrice: 135,
    priceBySizeOz: { 16: 135 },
    image: IMAGES.mango,
    drinkType: 'BLENDED',
    isPremium: false,
  },
  {
    id: 'lm-sparkling',
    storeId: 'lehmuhn',
    name: 'Sparkling Leh-muhn',
    description: 'Crisp sparkling Leh-muhn with citrus sparkle.',
    basePrice: 89,
    priceBySizeOz: { 16: 89, 22: 109 },
    image: IMAGES.icedTea,
    drinkType: 'SPARKLING',
    isPremium: false,
  },
  {
    id: 'lm-float',
    storeId: 'lehmuhn',
    name: 'Leh-muhn Float',
    description: 'Sparkling base with creamy float cap.',
    basePrice: 119,
    priceBySizeOz: { 16: 119, 22: 129 },
    image: IMAGES.icedTea,
    drinkType: 'SPARKLING',
    isPremium: false,
  },
  {
    id: 'lm-sparkling-matcha',
    storeId: 'lehmuhn',
    name: 'Sparkling Leh-muhn Matcha',
    description: 'Sparkling Leh-muhn with matcha finish.',
    basePrice: 119,
    priceBySizeOz: { 16: 119, 22: 129 },
    image: IMAGES.matcha,
    drinkType: 'SPARKLING',
    isPremium: false,
  },
  {
    id: 'lm-carrot-fresh-juice',
    storeId: 'lehmuhn',
    name: 'Carrot Fresh Juice Combo',
    description: 'Health is wealth series. Choose 2 fruits over carrot + honey base.',
    basePrice: 119,
    priceBySizeOz: { 16: 119, 22: 129 },
    image: IMAGES.citrus,
    drinkType: 'COLD',
    requiresFruitSelection: {
      min: 2,
      max: 2,
      options: ['Apple', 'Watermelon', 'Orange', 'Lemon'],
    },
    isPremium: false,
  },
  {
    id: 'kf-americano',
    storeId: 'kohfee',
    name: 'Americano',
    description: 'Bold espresso diluted for a clean finish.',
    basePrice: 109,
    image: IMAGES.espresso,
    menuGroup: 'HOT',
    subGroup: 'COFFEE',
    isFood: false,
    isPremium: false,
  },
  {
    id: 'kf-vietnamese-egg',
    storeId: 'kohfee',
    name: 'Vietnamese Egg Coffee',
    description: 'Silky whipped egg crema over robust coffee.',
    basePrice: 149,
    image: IMAGES.latte,
    menuGroup: 'HOT',
    allowedMenuGroups: ['HOT'],
    subGroup: 'COFFEE',
    isFood: false,
    isPremium: true,
  },
  {
    id: 'kf-cafe-latte',
    storeId: 'kohfee',
    name: 'Cafe Latte',
    description: 'Steamed milk and espresso with smooth body.',
    basePrice: 129,
    image: IMAGES.latte,
    menuGroup: 'HOT',
    subGroup: 'COFFEE',
    isFood: false,
    isPremium: false,
  },
  {
    id: 'kf-iced-latte',
    storeId: 'kohfee',
    name: 'Iced Latte',
    description: 'Cold milk and espresso over ice.',
    basePrice: 139,
    image: IMAGES.latte,
    menuGroup: 'COLD',
    allowedMenuGroups: ['COLD'],
    subGroup: 'COFFEE',
    isFood: false,
    isPremium: false,
  },
  {
    id: 'kf-cold-brew',
    storeId: 'kohfee',
    name: 'Cold Brew',
    description: '24-hour steeped coffee, smooth and chocolatey.',
    basePrice: 129,
    image: IMAGES.coldBrew,
    menuGroup: 'COLD',
    allowedMenuGroups: ['COLD'],
    subGroup: 'COFFEE',
    isFood: false,
    isPremium: false,
  },
  {
    id: 'kf-caramel-frappe',
    storeId: 'kohfee',
    name: 'Caramel Frappe',
    description: 'Coffee blended over ice with caramel drizzle.',
    basePrice: 149,
    image: IMAGES.frappe,
    menuGroup: 'BLENDED',
    subGroup: 'COFFEE',
    isFood: false,
    isPremium: false,
  },
  {
    id: 'kf-mocha-frappe',
    storeId: 'kohfee',
    name: 'Mocha Frappe',
    description: 'Chocolate coffee blend with creamy texture.',
    basePrice: 159,
    image: IMAGES.mocha,
    menuGroup: 'BLENDED',
    subGroup: 'COFFEE',
    isFood: false,
    isPremium: true,
  },
  {
    id: 'kf-signature-matcha',
    storeId: 'kohfee',
    name: 'Signature Matcha',
    description: 'Earthy matcha in creamy hot format.',
    basePrice: 139,
    image: IMAGES.matcha,
    menuGroup: 'HOT',
    subGroup: 'NON_COFFEE',
    isFood: false,
    isPremium: false,
  },
  {
    id: 'kf-iced-choco',
    storeId: 'kohfee',
    name: 'Iced Chocolate',
    description: 'Rich cocoa drink served iced.',
    basePrice: 129,
    image: IMAGES.mocha,
    menuGroup: 'COLD',
    allowedMenuGroups: ['COLD'],
    subGroup: 'NON_COFFEE',
    isFood: false,
    isPremium: false,
  },
  {
    id: 'kf-berry-smoothie',
    storeId: 'kohfee',
    name: 'Berry Smoothie',
    description: 'Mixed berry non-coffee blended drink.',
    basePrice: 149,
    image: IMAGES.citrus,
    menuGroup: 'BLENDED',
    subGroup: 'NON_COFFEE',
    isFood: false,
    isPremium: false,
  },
  {
    id: 'kf-grilled-cheese',
    storeId: 'kohfee',
    name: 'Grilled Cheese Sandwich',
    description: 'Toasted sandwich with melted cheese blend.',
    basePrice: 139,
    image: IMAGES.shop,
    menuGroup: 'FOOD',
    isFood: true,
    isPremium: false,
  },
  {
    id: 'kf-chicken-pesto',
    storeId: 'kohfee',
    name: 'Chicken Pesto Panini',
    description: 'Savory chicken panini with pesto spread.',
    basePrice: 179,
    image: IMAGES.shop,
    menuGroup: 'FOOD',
    isFood: true,
    isPremium: false,
  },
  {
    id: 'kf-croissant',
    storeId: 'kohfee',
    name: 'Butter Croissant',
    description: 'Flaky French-style pastry.',
    basePrice: 89,
    image: IMAGES.shop,
    menuGroup: 'FOOD',
    isFood: true,
    isPremium: false,
  },
  {
    id: 'kf-brownie',
    storeId: 'kohfee',
    name: 'Fudge Brownie',
    description: 'Dense chocolate brownie bar.',
    basePrice: 79,
    image: IMAGES.shop,
    menuGroup: 'FOOD',
    isFood: true,
    isPremium: false,
  },
];

export function getPriceForSize(product: Product, selectedSizeOz?: SizeOz): number {
  if (!selectedSizeOz) {
    return product.basePrice;
  }

  return product.priceBySizeOz?.[selectedSizeOz] ?? product.basePrice;
}

export function getCartItemUnitPrice(item: CartItem): number {
  const addOnsTotal = item.addOns.reduce((sum, addOn) => sum + addOn.extraCost, 0);
  const toppingsTotal = item.toppingsRemoved ? 0 : (item.toppingsCost ?? 0);

  return item.basePrice + addOnsTotal + toppingsTotal;
}

export function getCartItemLineTotal(item: CartItem): number {
  return getCartItemUnitPrice(item) * item.quantity;
}

const sampleOrderItem: CartItem = {
  cartItemId: 'sample-lm-just-16',
  productId: 'lm-just-lehmuhn',
  storeId: 'lehmuhn',
  name: 'Just Leh-muhn',
  description: 'Classic cold blend with lemon, chia, and nata de coco.',
  image: IMAGES.lemonJuice,
  basePrice: 69,
  quantity: 1,
  isPremium: false,
  selectedSizeOz: 16,
  selectedDrinkType: 'COLD',
  addOns: [],
  toppingsRemoved: false,
  toppingsLabel: 'Lemon + Chia + Nata de coco',
  toppingsCost: 15,
};

export const sampleOrders: Order[] = [
  {
    id: 'BJC-001',
    items: [{ ...sampleOrderItem, cartItemId: 'sample-lm-1', quantity: 2 }],
    total: 168,
    status: 'waiting_for_arrival',
    time: '10:30 AM',
    customerName: 'Maria Santos',
    orderType: 'Advance Order',
    paymentMethod: 'PAY_AT_STORE',
    paymentStatus: 'UNPAID',
    statusMessage: 'Prepare once you arrived in the store',
  },
  {
    id: 'BJC-002',
    items: [{ ...sampleOrderItem, cartItemId: 'sample-lm-2', quantity: 1, basePrice: 109, selectedSizeOz: 22 }],
    total: 109,
    status: 'preparing',
    time: '10:45 AM',
    customerName: 'Juan Dela Cruz',
    orderType: 'On-site',
    paymentMethod: 'ONLINE_PAYMONGO',
    paymentStatus: 'PAID',
    statusMessage: 'We\'re now processing your order',
  },
  {
    id: 'BJC-003',
    items: [{ ...sampleOrderItem, cartItemId: 'sample-lm-3', quantity: 1, basePrice: 135, selectedDrinkType: 'BLENDED', selectedSizeOz: 16 }],
    total: 135,
    status: 'ready',
    time: '11:00 AM',
    customerName: 'Ana Reyes',
    orderType: 'Advance Order',
    paymentMethod: 'ONLINE_PAYMONGO',
    paymentStatus: 'PAID',
    statusMessage: 'We\'re now processing your order',
  },
  {
    id: 'BJC-004',
    items: [{ ...sampleOrderItem, cartItemId: 'sample-kf-4', storeId: 'kohfee', name: 'Caramel Frappe', productId: 'kf-caramel-frappe', selectedMenuGroup: 'BLENDED', selectedSubGroup: 'COFFEE', selectedDrinkType: undefined, selectedSizeOz: 16, basePrice: 149, toppingsLabel: undefined, toppingsCost: 0 }],
    total: 149,
    status: 'completed',
    time: '9:15 AM',
    customerName: 'Carlo Mendoza',
    orderType: 'On-site',
    paymentMethod: 'ONLINE_PAYMONGO',
    paymentStatus: 'PAID',
    statusMessage: 'We\'re now processing your order',
  },
];
